version: 2.1

orbs:
  web-ui-orb: sandbox/web-ui-orb@2.1.0

references:
  version_js: &version_js 1
  version_cypress: &version_cypress 1
  image_name: &image_name '' #TODO - provide this
workflows:
  version: 2

  build-test-and-deploy:
    jobs:
      - web-ui-orb/dependencies:
          name: dependencies
          context: web-ui-npm
          cache_version_js_dependencies: *version_js
          cache_version_cypress_dependencies: *version_cypress
      - web-ui-orb/storybook-build:
          name: storybook-build
          cache_version_js_dependencies: *version_js
          requires:
            - dependencies
      - web-ui-orb/test:
          name: test
          cache_version_js_dependencies: *version_js
          requires:
            - dependencies
      - web-ui-orb/chromatic-snapshot:
          name: chromatic-snapshot
          cache_version_js_dependencies: *version_js
          requires:
            - dependencies
            - storybook-build
      - web-ui-orb/test-production-docker-image:
          name: test-production-docker-image
          image_name: *image_name
          cache_version_js_dependencies: *version_js
          requires:
            - dependencies
          context: org-global
      - web-ui-orb/build-and-deploy-static:
          cache_version_js_dependencies: *version_js
          name: build-and-deploy-static
          bucket_name: '' #TODO - provide this
          cdn_url: '' #TODO - provide this
          context: '' #TODO - provide this
          build_dir: ./.next
          filters:
            branches:
              only: master
          requires:
            - dependencies
      - web-ui-orb/build-and-deploy-container:
          name: deploy
          image_name: *image_name
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
          should_deploy: true
          context: org-global
          filters:
            branches:
              only: master
          requires:
            - test
            - build-and-deploy-static
            - test-production-docker-image
